'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const modules=Promise.all(['domain','service','store'].map(n=>import('../examples/panel/'+n+'.mjs')));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
async function fixture(){const [d,s,{createStore}]=await modules;const service=s.createDemoService({delay:0}),store=createStore(service);await store.refresh();return {d,s,store,service};}
test('project aggregates use integer cents, null coverage and matching daily window',async()=>{const{d,s}=await fixture();const snap=s.seedSnapshot();const x=d.summarize(snap.items);assert.deepEqual(x.cost,{value:7900,known:5,total:6});assert.equal(x.transfer.value,1904);assert.equal(d.chartData(snap.items,2).points.reduce((n,p)=>n+p.value,0),1904);assert.equal(x.running,4);});
test('numeric sort keeps null last in both directions and does not mutate source',async()=>{const {d,store}=await fixture();const original=store.get().snapshot.items.map(r=>r.id);for(const sort of ['cost-asc','cost-desc']){store.setView({sort});assert.equal(d.visibleItems(store.get()).at(-1).id,'sg-02');}assert.deepEqual(store.get().snapshot.items.map(r=>r.id),original);});
test('snapshot mutation outside the store cannot change application state',async()=>{const{store}=await fixture();const x=store.get();x.snapshot.items[0].cents=0;x.selected.push('x');assert.equal(store.get().snapshot.items[0].cents,1600);assert.deepEqual(store.get().selected,[]);});
test('selection, inspected identity and filtering are separate',async()=>{const{store}=await fixture();store.select('hk-01',true);store.inspect('sg-02');store.setView({sort:'cost-desc'});assert.deepEqual(store.get().selected,['hk-01']);assert.equal(store.get().detailId,'sg-02');store.setView({filter:'maintenance'});assert.deepEqual(store.get().selected,[]);assert.equal(store.get().detailId,'sg-02');});
test('read failure retains matching data and successful empty snapshot differs from no data',async()=>{const {store,service}=await fixture();service.failNext('read');assert.equal(await store.refresh(),false);assert.equal(store.get().snapshot.items.length,6);assert.ok(store.get().loadError);await store.refresh();assert.equal(store.get().loadError,null);});
for(const defect of ['duplicate','money','status','scope','series'])test('invalid incoming snapshot: '+defect,async()=>{const[d,s,{createStore}]=await modules;const good=s.seedSnapshot(),bad=structuredClone(good);if(defect==='duplicate')bad.items.push(bad.items[0]);if(defect==='money')bad.items[0].cents='1600';if(defect==='status')bad.items[0].status='probably-running';if(defect==='scope')bad.scope='sandbox';if(defect==='series')bad.items[0].daily=[1,2];const store=createStore({list:async()=>bad});assert.equal(await store.refresh(),false);assert.equal(store.get().snapshot,null);assert.ok(store.get().loadError);});
test('old scope succeeds after new scope without polluting the new project',async()=>{const[,s,{createStore}]=await modules;const jobs=[];const store=createStore({list(scope){const job=deferred();jobs.push({scope,...job});return job.promise;}});const old=store.refresh();const now=store.switchScope('sandbox');jobs[1].resolve(s.seedSnapshot('sandbox'));await now;jobs[0].resolve(s.seedSnapshot());await old;assert.equal(store.get().snapshot.scope,'sandbox');assert.equal(store.get().snapshot.items.length,1);});
test('old failure and finally cannot overwrite a newer in-flight request',async()=>{const[,s,{createStore}]=await modules;const jobs=[];const store=createStore({list(){const j=deferred();jobs.push(j);return j.promise;}});const a=store.refresh(),b=store.refresh();jobs[0].reject(new Error('old'));await a;assert.equal(store.get().loading,true);assert.equal(store.get().loadError,null);jobs[1].resolve(s.seedSnapshot());await b;assert.equal(store.get().loading,false);});
test('local mutation is not deleted by an earlier read snapshot',async()=>{const[,s,{createStore}]=await modules;const stale=deferred(),api=s.createDemoService({delay:0});let calls=0;const store=createStore({...api,list:scope=>++calls===1?api.list(scope):stale.promise});await store.refresh();const refresh=store.refresh();await store.create({name:'new-worker',region:'hk',plan:'nano'});stale.resolve(s.seedSnapshot());assert.equal(await refresh,false);assert.equal(store.get().snapshot.items.length,7);});
test('create failure keeps snapshot unchanged and duplicate activation sends once',async()=>{const{store,service}=await fixture();service.failNext('create');const draft={name:'worker-03',region:'hk',plan:'standard'};assert.equal(await store.create(draft),false);assert.equal(store.get().snapshot.items.length,6);assert.ok(store.get().create.error);const [a,b]=await Promise.all([store.create(draft),store.create(draft)]);assert.deepEqual([a,b],[true,false]);assert.equal(store.get().snapshot.items.length,7);});
test('cancelling the local creation before commit prevents addition',async()=>{const{store}=await fixture();const promise=store.create({name:'cancel-this',region:'hk',plan:'nano'});store.cancelCreate();assert.equal(await promise,false);await store.refresh();assert.equal(store.get().snapshot.items.length,6);});
test('status read changes only returned facts, not unknown fees or traffic',async()=>{const{store}=await fixture();await store.readStatus('sg-02');const r=store.get().snapshot.items.find(r=>r.id==='sg-02');assert.equal(r.status,'running');assert.equal(r.cents,null);assert.equal(r.transferGiB,null);});
test('independent object requests are allowed concurrently',async()=>{const{store}=await fixture();const a=store.readStatus('sg-02'),b=store.readStatus('tyo-02');assert.equal(store.get().reading.length,2);assert.deepEqual(await Promise.all([a,b]),[true,true]);assert.deepEqual(store.get().reading,[]);});
test('disposed state ignores pending completion and releases subscribers',async()=>{const[,s,{createStore}]=await modules;const j=deferred(),store=createStore({list:()=>j.promise});let changes=0;store.subscribe(()=>changes++);const p=store.refresh();const old=changes;store.dispose();j.resolve(s.seedSnapshot());await p;assert.equal(changes,old);assert.equal(store.get().snapshot,null);assert.throws(()=>store.subscribe(()=>{}),/disposed/);});
test('unsafe DTO strings stay text and CSV formulas are not executable cells',async()=>{const[d,s]=await modules;const{esc}=await import('../examples/panel/ui.mjs');const r=s.seedSnapshot().items[0];r.name='=1+1';const output=d.csv([r]);assert.ok(output.includes('"\'=1+1"'));assert.equal(esc('<img src=x>'),'&lt;img src=x&gt;');});
test('single-file build is deterministic, module-based and self-contained',()=>{const{build}=require('../examples/panel/build.cjs');const a=build(),b=build();assert.equal(a.html,b.html);assert.ok(a.html.includes('type="importmap"'));assert.ok(!a.html.includes('/*__STYLES__*/'));assert.ok(!/<(?:script|link)[^>]+(?:src|href)="https?:/.test(a.html));assert.equal(Object.keys(a.manifest).length,11);});

test('activity belongs to each project and survives switching away and back',async()=>{const{store}=await fixture();await store.create({name:'logged-worker',region:'hk',plan:'nano'});await store.switchScope('sandbox');assert.equal(store.get().events.length,0);await store.switchScope('northstar');assert.match(store.get().events[0].text,/logged-worker/);});

test('object read errors persist after finally and clear only on retry',async()=>{const{store,service}=await fixture();service.failNext('read');assert.equal(await store.readStatus('sg-02'),false);assert.ok(store.get().readErrors['sg-02']);assert.deepEqual(store.get().reading,[]);assert.equal(store.get().snapshot.items.find(r=>r.id==='sg-02').status,'unknown');await store.readStatus('sg-02');assert.equal(store.get().readErrors['sg-02'],null);});
